version: '3'

services:
  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=esercizio
           - MYSQL_USER=esercizio
           - MYSQL_PASSWORD=esercizio
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./mysql-volume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    build: ./springboot/docker/
    ports:
           - "8080:8080"
    environment:
           - spring_datasource_url=jdbc:mysql://db:3306/esercizio?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
           - spring_profiles_active=docker
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    build: ./angular
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80"
